"""Declare GCP templated resources to be created in each project"""

import pulumi
import pulumi_gcp as gcp

# Importing from main script:
# - gcp_projects: list[str] - GCP project IDs after project creation, sets up implicit dependency when using "project" arg for resource creation
# - generated_project_ids: list[str] - GCP project IDs generated by Python and used for project creation
# - emails: list[str] - emails of attendees
from __main__ import gcp_projects, generated_project_ids, emails

instances = []

# Loop on GCP projects and create resources
for project, generated_project_id in zip(gcp_projects, generated_project_ids):
    # Create a VM instance with a NGINX server installed with an startup script
    instance = gcp.compute.Instance(generated_project_id + '-vm', 
                                    name=generated_project_id + '-vm',
                                    project=project,
                                    zone='europe-west4-a', 
                                    machine_type='e2-micro',
                                    boot_disk={'initialize_params': {
                                        'image': 'debian-cloud/debian-12'
                                    }},
                                    network_interfaces=[{
                                        "access_configs": [{}],
                                        "network": "default"
                                        }],
                                    metadata_startup_script="apt update && apt upgrade; apt install nginx -y"
                                    )

    instances.append(instance.id)

pulumi.export('instances', instances)
